DROP TABLE IF EXISTS ANIMALS;

CREATE TABLE ANIMALS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  TYPE VARCHAR(250) NOT NULL,
  COLOR VARCHAR(250) NOT NULL
);

CREATE TABLE HOBBIES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TYPE VARCHAR(250) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  ANIMAL_ID INT,
  CONSTRAINT fk_animal FOREIGN KEY ("ANIMAL_ID") REFERENCES ANIMALS ("ID")
);

--INSERT INTO ANIMALS (TYPE, COLOR) VALUES
--  ('Dog', 'Black'),
--  ('Dog', 'Gold'),
--  ('Cat', 'Gray'),
--  ('Cat', 'White'),
--  ('Cat', 'Black');